import { Link } from 'react-router';
import { NexusEntry } from '../components/NexusEntry';
import { WorldWindow } from '../components/WorldWindow';

const CAPABILITIES=[['Dark-web monitoring','Configured mention feeds, source provenance and source health.'],['Threat correlation','Relationships between indicators, malware and adversarial infrastructure.'],['IOC analysis','IP, domain, URL and hash lookups grounded in source evidence.'],['Vulnerability intelligence','CPE matching, CVSS severity and CISA KEV context.'],['Actor mapping','Corroborated actor and intrusion-set relationships returned by the graph.'],['IoT security','Device discovery, behavioral baselines and explainable asset risk.'],['Network analysis','Observed assets, network topology and connected evidence.'],['Intelligence-driven response','Auditable decisions, role-controlled quarantine and recovery.']];

export function AboutPage(){
  return <div className="about-page"><section className="public-hero about-hero"><div className="hero-editorial"><p className="section-eyebrow">ABOUT DARKNET SENTINEL NEXUS</p><h1 className="about-brand-title">The invisible<br />network<br /><em>leaves signals<span className="hero-mark">.</span></em></h1><p className="public-lede">Intelligence begins where isolated observations become connected evidence.</p><div className="hero-ctas"><NexusEntry /></div></div><WorldWindow caption="MISSION / CONTEXT / EVIDENCE" /></section>
    <section className="public-section mission-grid"><article><p className="section-eyebrow">01 / MISSION</p><h2>Fragmented signals.<br /><span>Structured intelligence.</span></h2><p>Darknet Sentinel Nexus transforms fragmented underground signals into structured threat intelligence. It connects dark-web source mentions, adversarial infrastructure, indicators, vulnerability context and IoT asset risk so analysts can examine why a signal matters.</p></article><article><p className="section-eyebrow">02 / VISION</p><h2>Understand the<br /><span>adversarial ecosystem.</span></h2><p>Understand connected threats before they become operational incidents. Keep evidence visible, uncertainty explicit and responses traceable. Cyber threat correlation supplies context; explainable risk helps turn that context into a defensible decision.</p></article></section>
    <section className="public-section"><div className="public-section-heading"><div><p className="section-eyebrow">03 / ANALYST CAPABILITIES</p><h2>Built around evidence.</h2></div><Link to="/intelligence" className="public-text-link">Explore the research scope ↗</Link></div><div className="capability-grid">{CAPABILITIES.map(([name,description],i)=><article key={name}><span>{String(i+1).padStart(2,'0')}</span><h3>{name}</h3><p>{description}</p></article>)}</div></section>
    <section className="public-section"><div className="public-section-heading"><div><p className="section-eyebrow">04 / INVESTIGATION JOURNEY</p><h2>Trace the intelligence.</h2></div><p>A research workflow, with source provenance.<br />A relationship alone is not attribution.</p></div><ol className="intelligence-workflow">{['Signal','Discovery','Correlation','Risk','Response'].map((label,i)=><li key={label}><span>{String(i+1).padStart(2,'0')}</span><strong>{label}</strong><i aria-hidden="true">→</i></li>)}</ol><div className="public-final-cta"><h3>Observe. Correlate. Defend.</h3><NexusEntry /></div></section>
  </div>;
}
