import { useEffect, useState } from "react";
import { MetricBar } from "../components/MetricBar";
import { PageHeader } from "../layout/Shell";

// Generated by `make evaluate` / `make evaluate-report` and published into
// frontend/public/evaluation; every number here was measured by those runs.
interface Dist {
  n: number;
  p50: number | null;
  p95: number | null;
  max: number | null;
}

interface Quality {
  devices: Record<string, number>;
  alert_tpr: number | null;
  alert_fpr: number | null;
  quarantine_tpr: number | null;
  single_signal_quarantined: number | null;
  quarantine_fpr: number | null;
  unknown_flagged: number | null;
  vulnerable_alerted: number | null;
  vulnerable_quarantined: number | null;
  window_tpr: number | null;
  window_fpr: number | null;
  windows: Record<string, number>;
  correlation: { tp: number; fn: number; fp: number; tn: number; accuracy: number | null };
  latency_s: Record<string, { first_detection: Dist; first_alert: Dist; correlation: Dist }>;
  timing: Record<string, Dist>;
}

interface Summary {
  meta: Record<string, string | number | null>;
  calibration: {
    suggested?: Record<string, number>;
    margins?: { alert: number; quarantine: number };
    max_must_not_alert?: number;
    min_must_alert?: number;
    max_single_signal?: number;
    min_corroborated?: number;
  };
  phase3?: Quality;
  shipped?: Quality;
  calibrated: Quality;
  ws_latency_ms: { steady: Dist; burst: Dist; burst_size: number };
}

const PHASE3 = { medium: 25, high: 50, critical: 75 };

const pct = (v: number | null | undefined, digits = 1) => (v == null ? "n/a" : `${(v * 100).toFixed(digits)}%`);
const dist = (d: Dist | undefined, digits = 1) =>
  !d || !d.n ? "n/a" : `${d.p50?.toFixed(digits)} / ${d.p95?.toFixed(digits)} / ${d.max?.toFixed(digits)}`;

function parseCsv(text: string): Array<Record<string, string>> {
  const [head, ...lines] = text.trim().split(/\r?\n/);
  if (!head) return [];
  const cols = head.split(",");
  return lines.map((l) => {
    const cells = l.split(",");
    return Object.fromEntries(cols.map((c, i) => [c, cells[i] ?? ""]));
  });
}

export function EvaluationPage() {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [lab, setLab] = useState<Array<Record<string, string>>>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/evaluation/summary.json")
      .then((r) => (r.ok ? (r.json() as Promise<Summary>) : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then(setSummary)
      .catch((e: unknown) => setError(e instanceof Error ? e.message : String(e)));
    fetch("/evaluation/lab_runs.csv")
      .then((r) => (r.ok ? r.text() : ""))
      .then((t) => setLab(t ? parseCsv(t) : []))
      .catch(() => setLab([]));
  }, []);

  if (error) {
    return <p className="p-6 text-sm text-ink-300">No evaluation results published ({error}). Run `make evaluate`.</p>;
  }
  if (!summary) return <p className="p-6 text-xs text-ink-400">Loading evaluation…</p>;
  const before = summary.phase3 ?? summary.shipped;
  const after = summary.calibrated;
  const cal = summary.calibration;
  const quality: Array<[string, (q: Quality) => string]> = [
    ["Attacked devices that alerted", (q) => pct(q.alert_tpr)],
    ["Benign devices that alerted", (q) => pct(q.alert_fpr, 2)],
    ["Corroborated compromises auto-quarantined", (q) => pct(q.quarantine_tpr)],
    ["Flood alone auto-quarantined", (q) => pct(q.single_signal_quarantined)],
    ["Non-attacked devices auto-quarantined", (q) => pct(q.quarantine_fpr)],
    ["Unknown device flagged, not quarantined", (q) => pct(q.unknown_flagged)],
    ["Vulnerable-only device alerted", (q) => pct(q.vulnerable_alerted)],
    ["Vulnerable-only device auto-quarantined", (q) => pct(q.vulnerable_quarantined)],
    ["Attack windows flagged", (q) => pct(q.window_tpr)],
    ["Normal windows flagged", (q) => pct(q.window_fpr, 2)],
  ];
  const labMetrics: Array<[string, string, string]> = [
    ["flood_detect_s", "Flood start → anomaly on the live stream", "s"],
    ["c2_rescore_s", "C2 beacon → IOC re-score", "s"],
    ["auto_quarantine_s", "Corroborated attack → automatic quarantine", "s"],
    ["quarantine_apply_ms", "API quarantine → nftables rule (upper bound)", "ms"],
    ["release_apply_ms", "Release → rule removed (upper bound)", "ms"],
    ["recovery_s", "Expiry → automatic recovery", "s"],
    ["reconnect_s", "Release → device reconnects (whole s)", "s"],
  ];

  return (
    <div className="space-y-3 pb-6">
      <PageHeader
        title="Model / detection evaluation"
        subtitle={`Phase 7 · generated ${summary.meta.generated} on ${summary.meta.platform} · calibration seeds ${summary.meta.calibration_seeds}, held-out seeds ${summary.meta.eval_seeds}`}
      />
      <div className="mx-4 flex flex-wrap gap-2"><span className="technical-badge">PHASE 7</span><span className="technical-badge">CALIBRATION</span><span className="technical-badge">HELD-OUT SEEDS / {summary.meta.eval_seeds}</span></div>
      <p className="mx-4 max-w-4xl text-xs leading-relaxed text-ink-300">
        Six seeded scenarios run through the real pipeline, risk engine and response service on
        simulated traffic. Thresholds were derived on the calibration seeds by a fixed rule, then
        every metric below was measured on different (held-out) seeds. Traffic is simulated: the
        rates describe how DSN responds to these modelled signals, not field performance.
      </p>

      <div className="grid gap-3 px-4 xl:grid-cols-[1fr_1.4fr]">
        <section className="panel">
          <div className="panel-title">Threshold calibration</div>
          <div className="threshold-bars">{(["medium", "high", "critical"] as const).map(l => <div key={l}><span>{l}</span><strong>{cal.suggested?.[l] ?? "n/a"}</strong><MetricBar value={cal.suggested?.[l]} tone={l} /></div>)}</div>
          <table className="w-full text-xs">
            <thead className="text-[10px] tracking-wider text-ink-400 uppercase">
              <tr>
                <th className="px-3 py-1.5 text-left">level</th>
                <th className="px-3 py-1.5 text-right">Phase 3</th>
                <th className="px-3 py-1.5 text-right">calibrated (shipped)</th>
              </tr>
            </thead>
            <tbody>
              {(["medium", "high", "critical"] as const).map((l) => (
                <tr key={l} className="border-t border-ink-800">
                  <td className="px-3 py-1.5">{l}</td>
                  <td className="px-3 py-1.5 text-right font-mono text-ink-400">{PHASE3[l]}</td>
                  <td className="px-3 py-1.5 text-right font-mono">{cal.suggested?.[l] ?? "n/a"}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="px-3 py-2 text-[11px] leading-relaxed text-ink-400">
            Margins on calibration seeds: alert {cal.margins?.alert} points, quarantine{" "}
            {cal.margins?.quarantine} points. Automatic quarantine additionally needs observed
            evidence of compromise; exposure alone goes to operator review.
          </p>
        </section>

        <section className="panel">
          <div className="panel-title">Detection quality (held-out seeds)</div>
          <table className="w-full text-xs">
            <thead className="text-[10px] tracking-wider text-ink-400 uppercase">
              <tr>
                <th className="px-3 py-1.5 text-left">metric</th>
                <th className="px-3 py-1.5 text-right">Phase 3</th>
                <th className="px-3 py-1.5 text-right">calibrated</th>
              </tr>
            </thead>
            <tbody>
              {quality.map(([label, fn]) => (
                <tr key={label} className="border-t border-ink-800">
                  <td className="px-3 py-1.5">{label}</td>
                  <td className="px-3 py-1.5 text-right font-mono text-ink-400">{before ? fn(before) : "n/a"}</td>
                  <td className="px-3 py-1.5 text-right font-mono">{fn(after)}<MetricBar value={fn(after) === "n/a" ? null : parseFloat(fn(after))} /></td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="px-3 py-2 text-[11px] text-ink-400">
            Correlation: {after.correlation.tp} of {after.correlation.tp + after.correlation.fn} C2 contacts
            correlated, {after.correlation.fp} of {after.correlation.fp + after.correlation.tn} decoys
            (accuracy {pct(after.correlation.accuracy)}). Devices:{" "}
            {Object.entries(after.devices).map(([k, v]) => `${v} ${k}`).join(", ")}.
          </p>
        </section>
      </div>

      <section className="panel mx-4"><div className="panel-title">Detection latency / simulated seconds</div><div className="latency-grid">{Object.entries(after.latency_s).filter(([,v]) => v.first_detection.n).map(([scenario, v]) => <div key={scenario} className="latency-scenario"><h3>{scenario.replace(/_/g, " ")}</h3><span className="section-eyebrow">FIRST DETECTION</span><dl>{(["p50", "p95", "max"] as const).map(k => <div key={k}><dt>{k}</dt><dd>{v.first_detection[k]?.toFixed(0) ?? "n/a"}<small> s</small></dd></div>)}</dl></div>)}</div></section>
      <div className="grid gap-3 px-4 xl:grid-cols-2">
        <section className="panel">
          <div className="panel-title">Latency, simulated time (p50 / p95 / max, s)</div>
          <table className="w-full text-xs">
            <thead className="text-[10px] tracking-wider text-ink-400 uppercase">
              <tr>
                <th className="px-3 py-1.5 text-left">scenario</th>
                <th className="px-3 py-1.5 text-right">first detection</th>
                <th className="px-3 py-1.5 text-right">first alert</th>
                <th className="px-3 py-1.5 text-right">IOC correlation</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(after.latency_s)
                .filter(([, v]) => v.first_detection.n || v.first_alert.n)
                .map(([k, v]) => (
                  <tr key={k} className="border-t border-ink-800">
                    <td className="px-3 py-1.5">{k.replace(/_/g, " ")}</td>
                    <td className="px-3 py-1.5 text-right font-mono">{dist(v.first_detection, 0)}</td>
                    <td className="px-3 py-1.5 text-right font-mono">{dist(v.first_alert, 0)}</td>
                    <td className="px-3 py-1.5 text-right font-mono">{dist(v.correlation, 0)}</td>
                  </tr>
                ))}
            </tbody>
          </table>
        </section>
        <section className="panel">
          <div className="panel-title">Compute and delivery (p50 / p95 / max)</div>
          <table className="w-full text-xs">
            <tbody>
              {[
                ["Risk assessment per device (ms)", dist(after.timing.risk_assess_ms, 2)],
                ["Quarantine call, dry-run driver (ms)", dist(after.timing.quarantine_ms, 2)],
                ["Recovery after expiry, sweep only (s, simulated)", dist(after.timing.recovery_s)],
                ["Live events, steady 50/s (ms, loopback)", dist(summary.ws_latency_ms.steady)],
                [`Live events, burst of ${summary.ws_latency_ms.burst_size} (ms, loopback)`, dist(summary.ws_latency_ms.burst)],
              ].map(([k, v]) => (
                <tr key={k} className="border-t border-ink-800">
                  <td className="px-3 py-1.5">{k}</td>
                  <td className="px-3 py-1.5 text-right font-mono">{v}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      </div>

      {lab.length > 0 && (
        <section className="panel mx-4">
          <div className="panel-title">Virtual lab, end to end (wall clock, real nftables)</div>
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead className="text-[10px] tracking-wider text-ink-400 uppercase">
                <tr>
                  <th className="px-3 py-1.5 text-left">measurement</th>
                  {lab.map((r) => (
                    <th key={r.run} className="px-3 py-1.5 text-right">
                      run {r.run}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {labMetrics.map(([key, label, unit]) => (
                  <tr key={key} className="border-t border-ink-800">
                    <td className="px-3 py-1.5">{label}</td>
                    {lab.map((r) => (
                      <td key={r.run} className="px-3 py-1.5 text-right font-mono">
                        {r[key] ? `${r[key]} ${unit}` : "missed"}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}

      <div className="grid gap-3 px-4 xl:grid-cols-2">
        {[
          ["score_distribution.png", "Risk score per device and scenario (held-out seeds)"],
          ["detection_latency.png", "Detection latency per attack"],
          ["ws_latency.png", "Live event latency (cumulative)"],
        ].map(([file, alt]) => (
          <figure key={file} className="panel overflow-hidden">
            <img src={`/evaluation/${file}`} alt={alt} className="w-full bg-[#fcfcfb]" loading="lazy" />
            <figcaption className="px-3 py-2 text-[11px] text-ink-400">{alt}</figcaption>
          </figure>
        ))}
      </div>
    </div>
  );
}
