import { useMemo, useState, type FormEvent } from "react";
import { api } from "../api/client";
import type { CveMatch } from "../api/types";
import { PageHeader } from "../layout/Shell";
import { useIntelligenceMetadata } from "../hooks/useIntelligenceMetadata";
import { useLive } from "../live/LiveContext";
import { NexusScene } from "../visuals/NexusScene";
import type { IntelligenceNode } from "../visuals/model";
export function VulnerabilitiesPage(){
  const {counts}=useIntelligenceMetadata();
  const {state}=useLive();
  const [cpe,setCpe]=useState('');const [result,setResult]=useState<CveMatch[]|null>(null);const [error,setError]=useState<string|null>(null);const [loading,setLoading]=useState(false);const [selected,setSelected]=useState<string|null>(null);
  const products=[...new Set(Object.values(state.nodes).flatMap(n=>n.device.cpes.map(c=>c.cpe)))];
  const nodes=useMemo<IntelligenceNode[]>(()=>result?result.map(c=>({id:c.vulnerability_id,label:c.cve,kind:'Vulnerability',color:c.kev?'#ff315a':'#ff9f2d',detail:`CVSS ${c.cvss_score??'not supplied'} / ${c.cvss_severity??'unclassified'} / ${c.kev?'CISA KEV':'Not in KEV'}`})):['CVE','CVSS','CPE','Affected product','Exploitability','CISA KEV'].map((label,i)=>({id:`schema-${i}`,label,kind:'Research dimension',detail:'Vulnerability evidence schema; no specific vulnerability or score is implied.'})),[result]);
  const focus=result?.find(c=>c.vulnerability_id===selected);
  const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError(null);setSelected(null);try{setResult(await api.cves(cpe.trim()));}catch(e){setResult(null);setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}};
  return <div className="analyst-workspace vulnerability-workspace"><PageHeader title="Vulnerability intelligence" subtitle="Product exposure, CVSS evidence and CISA Known Exploited Vulnerabilities." /><div className="workspace-command-line"><span className="section-eyebrow">EXPOSURE / PRODUCT INTELLIGENCE</span><span className="technical-badge">CVE / CPE 2.3</span></div><div className="workspace-metrics"><div><span>Vulnerability objects</span><strong>{counts?counts.Vulnerability??0:'—'}</strong></div><div><span>CPE objects</span><strong>{counts?counts.CPE??0:'—'}</strong></div><div><span>Matching CVEs</span><strong>{result?.length??'—'}</strong></div><div><span>CISA KEV matches</span><strong>{result?result.filter(c=>c.kev).length:'—'}</strong></div></div>
    <form className="workspace-query panel" onSubmit={submit}><label htmlFor="vulnerability-cpe">PRODUCT EXPOSURE LOOKUP</label><div><span className="terminal-prompt" aria-hidden="true">&#10095;</span><input id="vulnerability-cpe" className="input" aria-label="Vulnerability CPE" placeholder="cpe:2.3:..." value={cpe} maxLength={512} onChange={e=>setCpe(e.target.value)} /><button className="btn command-action" disabled={!cpe.trim()||loading}>{loading?'Matching...':'Look up CVEs'}</button></div>{products.length>0&&<select className="input observed-product" aria-label="Observed product" value={products.includes(cpe)?cpe:''} onChange={e=>setCpe(e.target.value)}><option value="">Select an observed asset product</option>{products.map(p=><option key={p} value={p}>{p}</option>)}</select>}</form>{error&&<p className="workspace-error" role="alert">{error}</p>}
    <div className="workspace-main"><section className="panel workspace-network"><div className="command-section-title"><div><span className="section-eyebrow">PRODUCT / VULNERABILITY EVIDENCE</span><h2>Exposure constellation</h2></div></div><NexusScene title="Vulnerability evidence constellation" mode="specimen" nodes={nodes} selected={selected} onSelect={setSelected} illustrative={!result} caption={result?'CVE MATCHES / RETURNED PRODUCT EVIDENCE':'VULNERABILITY EVIDENCE / SCHEMA'} /></section><aside className="panel intelligence-inspector"><span className="section-eyebrow">VULNERABILITY / EVIDENCE BRIEFING</span><h2>{focus?.cve??'Evaluate the exposure.'}</h2>{focus?<><span className={`chip ${focus.kev?'bg-critical/15 text-critical':'bg-ink-700 text-ink-300'}`}>{focus.kev?'CISA KEV':'Not in KEV'}</span><dl><dt>CVSS</dt><dd>{focus.cvss_score??'Not supplied'}</dd><dt>Severity</dt><dd>{focus.cvss_severity??'Not supplied'}</dd><dt>Product criteria</dt><dd className="break-all font-mono">{focus.criteria}</dd><dt>Match</dt><dd>{focus.match}</dd><dt>KEV ransomware</dt><dd>{focus.kev_ransomware?'Reported':'Not reported'}</dd><dt>KEV due date</dt><dd>{focus.kev_due_date??'Not supplied'}</dd></dl></>:<p>Choose an observed product or enter a CPE identifier. Select a returned CVE to inspect its severity, match basis and KEV metadata.</p>}<div className="analyst-note"><span className="section-eyebrow">EXPOSURE IS NOT COMPROMISE</span><p>A product match supports vulnerability review. Automatic containment still requires the application's existing evidence and response policy.</p></div></aside></div>
    <section className="panel workspace-results"><div className="command-section-title"><div><span className="section-eyebrow">MATCHED / VULNERABILITY RECORDS</span><h2>CVE findings</h2></div></div><div className="overflow-x-auto"><table><thead><tr><th>CVE</th><th>CVSS</th><th>Severity</th><th>CISA KEV</th><th>Match basis</th><th>Affected product</th></tr></thead><tbody>{result?.map(c=><tr key={c.cve} tabIndex={0} onClick={()=>setSelected(c.vulnerability_id)} onKeyDown={e=>e.key==='Enter'&&setSelected(c.vulnerability_id)}><td className="font-mono">{c.cve}</td><td>{c.cvss_score??'—'}</td><td>{c.cvss_severity??'—'}</td><td><span className={`chip ${c.kev?'bg-critical/15 text-critical':'bg-ink-700 text-ink-300'}`}>{c.kev?'Known exploited':'Not in KEV'}</span></td><td>{c.match}</td><td className="font-mono">{c.criteria}</td></tr>)}</tbody></table></div>{!result?.length&&<div className="workspace-empty">{result?'No matching CVEs were returned.':'Run a product lookup to load vulnerability evidence.'}</div>}</section>
  </div>;
}
