#!/usr/bin/env python3
"""Generate frontend/src/generated/events.ts from backend/app/core/event_schema.py.

    cd backend && uv run python ../scripts/gen_event_types.py          # write
    cd backend && uv run python ../scripts/gen_event_types.py --check  # CI: fail if stale

The TypeScript is derived from the pydantic models' JSON Schema, so the
dashboard compiles against exactly the payloads ``EventBus.emit`` accepts.
Only the JSON-Schema subset those models use is supported; anything else fails
loudly instead of degrading to ``any``.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from pydantic.json_schema import models_json_schema  # noqa: E402

from app.core.event_schema import PAYLOADS  # noqa: E402

OUT = ROOT / "frontend" / "src" / "generated" / "events.ts"
HEADER = """\
// GENERATED by scripts/gen_event_types.py from backend/app/core/event_schema.py.
// Do not edit by hand: run `make gen-types` (CI fails if this file is stale)."""


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(dict.fromkeys(ts_type(s) for s in schema["anyOf"]))
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(v) for v in schema["enum"])
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in ("number", "integer"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        inner = ts_type(schema.get("items", {}))
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if kind == "object":
        if "properties" in schema:
            raise SystemExit("inline object schemas are not supported; use a model")
        extra = schema.get("additionalProperties", True)
        value = "unknown" if extra in (True, {}) else ts_type(extra)
        return f"Record<string, {value}>"
    if schema == {}:
        return "unknown"
    raise SystemExit(f"unsupported JSON schema: {schema}")


def _literal(value: Any) -> str:
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def interface(name: str, schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for prop, sub in schema.get("properties", {}).items():
        # Defaults are filled by the backend before sending, so every field is
        # present on the wire; "optional" in the model means nullable/defaulted.
        _ = prop in required
        lines.append(f"  {prop}: {ts_type(sub)};")
    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    models = list(dict.fromkeys(PAYLOADS.values()))
    _, top = models_json_schema(
        [(m, "serialization") for m in models], ref_template="#/$defs/{model}"
    )
    defs: dict[str, Any] = top["$defs"]
    parts = [HEADER]
    for name in sorted(defs):
        parts.append(interface(name, defs[name]))
    types = sorted(PAYLOADS)
    parts.append(
        "export type EventType =\n" + "\n".join(f'  | "{t}"' for t in types) + ";"
    )
    parts.append(
        "export interface EventPayloads {\n"
        + "\n".join(f'  {t}: {PAYLOADS[t].__name__};' for t in types)
        + "\n}"
    )
    parts.append(
        "/** Wire envelope: Socket.IO `events` batches and GET /api/events. */\n"
        "export type DsnEvent = {\n"
        "  [T in EventType]: {\n"
        "    seq: number;\n"
        "    type: T;\n"
        "    ts: string;\n"
        "    node_id: string | null;\n"
        "    payload: EventPayloads[T];\n"
        "  };\n"
        "}[EventType];"
    )
    parts.append(
        "export const EVENT_TYPES: readonly EventType[] = [\n"
        + "\n".join(f'  "{t}",' for t in types)
        + "\n];"
    )
    return "\n\n".join(parts) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            sys.exit(f"{OUT.relative_to(ROOT)} is stale: run `make gen-types`")
        print("event types up to date")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
